version: '3'

tasks:
  has:golangci-lint:
    desc: Check if golangci-lint is installed
    cmds:
      - |
        if ! command -v golangci-lint > /dev/null; then
          echo "golangci-lint not found missing. To install see https://github.com/golangci/golangci-lint/releases"
          exit 1
        fi

  lint:
    desc: Run lint checks
    deps:
      - task: has:golangci-lint
    cmds:
      - golangci-lint run

  test:
    desc: Run test suites
    cmds:
      - go test -v ./...

  build:
    desc: Compile the project
    cmds:
      - go build -o ./bin/ -v ./...

